name: Test ELS Testplan Dashboard for Codespaces

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flask-testing
    
    - name: Run basic tests
      run: |
        python -c "import app; print('✅ App imports successfully')"
        python -c "from app import app; print('✅ Flask app created successfully')"
    
    - name: Test Codespaces configuration
      run: |
        echo "✅ Testing Codespaces configuration..."
        test -f .devcontainer/devcontainer.json && echo "✅ devcontainer.json exists"
        test -f .devcontainer/setup.sh && echo "✅ setup.sh exists"
        test -f GITHUB_CODESPACES_DEPLOYMENT.md && echo "✅ Deployment guide exists"
    
    - name: Validate application structure
      run: |
        echo "✅ Validating application structure..."
        test -d templates && echo "✅ Templates directory exists"
        test -d uploads && echo "✅ Uploads directory exists"
        test -f requirements.txt && echo "✅ Requirements file exists"
        test -f app.py && echo "✅ Main application file exists"

  codespaces-ready:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Verify Codespaces readiness
      run: |
        echo "🚀 ELS Testplan Dashboard is ready for GitHub Codespaces!"
        echo ""
        echo "📋 To use the dashboard:"
        echo "1. Go to the repository on GitHub"
        echo "2. Click 'Code' → 'Codespaces' → 'Create codespace on main'"
        echo "3. Wait for automatic setup (2-3 minutes)"
        echo "4. Run: python app.py"
        echo "5. Open the forwarded port 5000"
        echo "6. Login with: admin / admin123"
        echo ""
        echo "📖 Full documentation: GITHUB_CODESPACES_DEPLOYMENT.md"
